import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import "bootstrap/dist/css/bootstrap.min.css";
import SessionWrapper from "@/components/SessionWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          {children}
          {/* Bootstrap JS & Popper */}
          <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVDv+5tYQFqxqgTw/8a6++nqh3Lj6iZqJhIapOlfTbUQq+fMFhGE8fEUk+I/"
            crossOrigin="anonymous"
            defer
          ></script>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BOzY2URBtvUwhp+NOCpH5CzR1/9BoOZsV7I+1Z4SN2NEvlxNq4r7+zVqULh1YqaV"
            crossOrigin="anonymous"
            defer
          ></script>
        </SessionWrapper>
      </body>
    </html>
  );
}
